
// USER INFOMATION
export const UPDATE_ACCOUTN = 'UPDATE_ACCOUTN';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_TELPHONE = 'UPDATE_TELPHONE';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';
export const UPDATE_NICKNAME = 'UPDATE_NICKNAME';
export const UPDATE_SEX = 'UPDATE_SEX';
export const UPDATE_ID = 'UPDATE_ID';
export const UPDATE_SCORE = 'UPDATE_SCORE';
